services:
  live:
    build: /etc/docker/container/live
    ports: 
      - "4000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.live.rule=Host(`arbispotter.com`) && PathPrefix(`/app`)"
      - "traefik.http.services.live.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.live-headers.headers.customrequestheaders.X-Real-IP=$$remote_addr"
      - "traefik.http.middlewares.live-headers.headers.customrequestheaders.X-Forwarded-For=$$proxy_add_x_forwarded_for"
      - "traefik.http.middlewares.live-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.live-headers.headers.customrequestheaders.X-Forwarded-Host=$$host"
      - "traefik.http.middlewares.live-headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"  
    networks:
      - traefik_web
networks:
  traefik_web:
    external: true
