name: Deploy
on:
  push:
    branches:
      - staging
      - main
jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy staging
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_FE_PK }}
          passphrase: ${{ secrets.PASSPHRASE }}
          command_timeout: 30m
          script: |
            docker builder prune -f
            git --work-tree=/etc/docker/container/staging --git-dir=/etc/docker/container/staging/.git reset --hard
            git --work-tree=/etc/docker/container/staging --git-dir=/etc/docker/container/staging/.git pull
            cd /etc/docker/container/staging
            docker compose -f docker-compose.staging.yml up --build -d
  deploy-live:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy live
        timeout-minutes: 30
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST_LIVE}}
          command_timeout: 30m
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_FE_PK }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            docker builder prune -f
            git --work-tree=/etc/docker/container/live --git-dir=/etc/docker/container/live/.git reset --hard
            git --work-tree=/etc/docker/container/live --git-dir=/etc/docker/container/live/.git pull
            cd /etc/docker/container/live
            docker compose -f docker-compose.live.yml up --build -d 