name: Deploy
on:
  push:
    branches:
      - staging
      - live
jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment"
          # Add your deployment script/commands here

  deploy-live:
    if: github.ref == 'refs/heads/live'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to live
        run: |
          echo "Deploying to live environment"
          # Add your deployment script/commands here
